### ISSUE TITLE
Consider adding a LICENSE or specifying that there isn't one

### ISSUE THREAD

**Issue by vlmutolo** [m4lwhere/pySpray#1]
If your intention is to open-source this project, you should add an open source license. This is usually done by adding a top-level `LICENSE` file in the repository.

GitHub has a nice article about both [choosing a license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) and [actually adding it to the project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

---

Alternatively, if you don't want other people to use the code, consider explicitly stating that in the README.

**Comment by m4lwhere** [comment]
perhaps i will consider that if you leave a star 🌟⭐🤩
